### ISSUE TITLE
error: Dependency 'fmake' could not be resolved

### ISSUE THREAD

**Issue by l2dy** [holzschu/network_ios#16]
I could not compile the framework with `./compile_network_ios.sh`.

```
$ ./compile_network_ios.sh
Fetching https://github.com/yury/FMake
Fetched https://github.com/yury/FMake (1.25s)
Computing version for https://github.com/yury/FMake
error: Dependencies could not be resolved because no versions of 'fmake' match the requirement 0.0.16..<1.0.0 and root depends on 'fmake' 0.0.16..<1.0.0.
error: 'xcfs': binary target 'ios_system' could not be mapped to an artifact with expected name 'ios_system'
```

**Comment by holzschu** [comment]
I might need help with that one. I have no idea what's happening, and I don't see any significant difference with iOS_system's version of package.swift. There was a tiny difference, so I've pushed a new version.

**Comment by l2dy** [comment]
It's probably because https://github.com/yury/FMake does not have any Git tag.

Replacing it with https://github.com/blinksh/FMake in `xcfs/Package.swift` resolves the issue. See https://github.com/l2dy-forks/network_ios/commit/994eabdbb3832d0329ff06db68720d1d27ccf913 for a patch.

**Comment by holzschu** [comment]
Thanks a lot; I've pushed the version with your fix.

**Comment by l2dy** [comment]
Fixed. Closing.
