### ISSUE TITLE
ping6 does not reset icmp_seq on consecutive runs

### ISSUE THREAD

**Issue by l2dy** [holzschu/network_ios#17]
`ping_main` in ping.c resets counters to 0. `ping6_main` should do that as well.

https://github.com/holzschu/network_ios/blob/a1140568cb23616b89c1ecfe585e526d9db39d79/sources/ping.c#L318-L323

**Comment by holzschu** [comment]
Thanks, it is done (in the source).

**Comment by l2dy** [comment]
@holzschu Have you pushed your changes to GitHub?

**Comment by holzschu** [comment]
I have now.

**Comment by l2dy** [comment]
It works. Thank you!
